language: c
compiler: gcc
sudo: required
dist: trusty
cache:
  - apt

before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:ricotz/testing -y
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake valac libgtk-3-dev libkeybinder-3.0-dev libxml2-utils gettext

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_TESTS=ON .
  - make
  - make test
  - # echo "deb http://archive.ubuntu.com/ubuntu/ xenial main universe multiverse restricted" > sources.list
  - # sudo mv sources.list /etc/apt/sources.list
  - # sudo apt-get update
  - sudo apt-get -y install checkinstall libav-tools
  - sudo checkinstall --pkgname=app --pkgversion="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; rm usr/local ; find . 
  - cp ./usr/share/applications/*.desktop . 
  - cp ./usr/share/icons/hicolor/256x256/apps/peek.png . 
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage 
  - cp $(which avconv) $(which ffmpeg) ./appdir/usr/bin
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/peek -bundle-non-qt-libs -executable=./appdir/usr/bin/avconv -executable=./appdir/usr/bin/ffmpeg
  - ( cd usr/share/glib-2.0/schemas/ ; glib-compile-schemas . )
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/peek -appimage 
  - curl --upload-file ./Peek-*.AppImage https://transfer.sh/Peek-x86_64.AppImage 

deploy:
  provider: launchpad
  slug: "~peek-developers/peek/+git/peek"
  oauth_token:
    secure: i6JfL4MPjIeZjs3a4hcVAP1ck86b0ENmMV5meKtUs8U7q8VH76Aaglr2SJQNqLmAC5SzLPoJuQoDZEwIAxQCmw1l1UjggjZnLcIXnWuJMJG6220Jel9OA9Q+mTM0Zk3yOzTOzwjTebIuUscb3h19Q2j9jU5Doo3703Z7b72B+nsVes14o5/xlfE8+LBeISeg0tsW8Ck54ssG10nzsaDV2GshJQG8uR1e6FQ2OLuDl1MqZ6TX9rY4GlS7Of8mgW4Pdp7ULrcgGGKzxOLXz0asNp+NuPkeO3qKsYghp/5/Y18TVgreIJ1Qf/OWcyrxAEdAqVznIXXh1iptpK/Czk7iudMtQqqnd/YzSUKUhzOw+hdyYQO2m8Z30WSTbhm+XcVxYkM4KwpFQ04F5RIFHGMA7pn1ihaELO9WbPKwp4e+L3C4lEs9kjoy+756wH7LUE5LILcN+iPnmpzg8SR4sx99te2eboh6nF822GagBd1BYNe0Rw2iftHbGC+NS846CEtFOKCKwIpfD0rC2aGAB1c63d5GSWSDE7YztmYzLS2Eq/xx4ELuQxUNY0/9P5fMQwt0R8Q3Osj70ZBm2mLN+9bER3QVruZ81Zbi0YEU9PGAQvGAxwwP18UDZpMiSR1beG33tXLfpDHR54dkJDT2yWxUa5ITTwvqiGEVzqz2bPqklsM=
  oauth_token_secret:
    secure: ZQllTTeB8oWeoQ+O+TKoI7VagUyAMuFGGUfeuGGVvwR0i0SnR4m+RfA39iwlvqSGO33vMxGycj741bgJmCmslyIteTkgASMyPEiqHA37SRh6IIQQT9wInw8MV17Biykj+rgEryv+b7+6rPLXtESC144/1I5YuGYTuNIGQJZmCUdeZMFkM7XR/h41vXahaZPjJio1t/d/m36JzkP1urGZz1yFvnV6AJHrWP6JOFG7r4+7c4EKELo/jnsWjfxfcSRyQX3DkEfUcSSgn9ZA0n6i9Tq2AhaXYLnQXCLm1DAroBWdf3OHfi5PBsN4hraRIweB1aLilpfDuV2Q7WYVlvt6KfCR8GFSJR+vDX9KjhiqwvyqKZdkoe1vIhcdeE1vqXjW3b6YYnsBVi2ccY4qQZhwOuTz3KoygPSqpaFAeRs7jyu9kYRAjJvxgLY3bSyRYWSfHYLTGgxB/ZTl4oM5AUOFYXRcegiqpeGecCrKGBnG8c+YiYq+O/otI2RSlfV5k0q0UNDJRDxOo7ifZT9SdvKnDOqBpWMlKOA3NS6jItwcfDKwdjcZM4uer6VxsYOTS5AaJlm2SIjSrY1tdrC3F9VvZ+OX2tWluMtqJPW5GGspUfkoyrd+Udc8vDID1/ZutbtxA03BC2YSPbZlcWsw4klRv1h7eOfN5n52EQM9cLaPeg4=
