language: c
compiler: gcc
sudo: true
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake valac libgtk-3-dev libxml2-utils gettext
script:
  - cmake -DBUILD_TESTS=ON .
  - make
  - make test
