language: c
compiler: gcc
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - cmake
    - valac
    - libgtk-3-dev
    - libxml2-utils
    - gettext
sudo: false
script:
  - cmake -DBUILD_TESTS=ON .
  - make
  - make test
