name: peek
version: '0.8.0+git'
icon: data/icons/512x512/peek.png
summary: An animated GIF recorder with an easy to use interface.
description: |
  Peek creates animated GIF screencasts using ffmpeg and imagemagick. It was
  built for the specific use case of recording screen areas, e.g., for easily
  showing UI features of your own apps or for showing a bug in bug reports. It
  is not a general purpose screencast app with extended features and it never
  will be.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  peek:
    command: desktop-launch peek
    desktop: usr/share/applications/com.uploadedlobster.peek.desktop
    plugs:
      - x11
      - unity7
      - home
      - gsettings

parts:
  peek:
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DGSETTINGS_COMPILE=OFF
    source: .
    after:
      - desktop-gtk3
    build-packages:
      - libgtk-3-dev
      - gettext
      - valac
    stage-packages:
      - libcanberra-gtk3-module
      - ffmpeg
      - imagemagick
    install: |
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      [[ ! -f $SNAPCRAFT_PART_INSTALL/usr/bin/convert ]] && ln -s $SNAPCRAFT_PART_INSTALL/usr/bin/convert-im6 $SNAPCRAFT_PART_INSTALL/usr/bin/convert
