name: peek
version: '1.0.3+git'
icon: data/icons/512x512/com.uploadedlobster.peek.png
summary: Simple screen recorder with an easy to use interface
description: |
  Peek makes it easy to create short screencasts of a screen area. It was built
  for the specific use case of recording screen areas, e.g. for easily showing
  UI features of your own apps or for showing a bug in bug reports. With Peek
  you simply place the Peek window over the area you want to record and press
  "Record". Peek is optimized for generating animated GIFs, but you can also
  directly record to WebM or MP4 if you prefer.
grade: stable
confinement: classic

apps:
  peek:
    command: desktop-launch launch-peek
    desktop: share/applications/com.uploadedlobster.peek.desktop
    # plugs:
    #   - x11
    #   - unity7
    #   - home
    #   - gsettings
  # ffmpeg:
  #   command: ffmpeg
  # convert:
  #   command: convert

# slots:
#   session-dbus-interface:
#     interface: dbus
#     name: com.uploadedlobster.peek
#     bus: session

parts:
  peek:
    plugin: cmake
    configflags:
      - -DGSETTINGS_COMPILE=OFF
      - -DDISABLE_GNOME_SHELL=ON 
    source: .
    # source: /media/sf_devel/peek
    source-type: git
    after:
      - desktop-gtk3
    build-packages:
      - libgtk-3-dev
      - libkeybinder-3.0-dev
      - gettext
      - valac
    stage-packages:
      - libcanberra-gtk3-module
      - libkeybinder-3.0-0
    install: |
      cp data/extra/com.canonical.Unity.gschema.xml $SNAPCRAFT_PART_INSTALL/share/glib-2.0/schemas
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/share/glib-2.0/schemas
    prime:
      - -usr/share/doc
      - -usr/share/man

  launcher:
    plugin: dump
    source: data/snapcraft/
    organize:
      launch-peek: bin/launch-peek
    install: |
      chmod 0755 $SNAPCRAFT_PART_INSTALL/launch-peek

  # snapd-xdg-open:
  #   plugin: dump
  #   source: https://github.com/ubuntu-core/snapd-xdg-open.git
  #   organize:
  #     data/xdg-open: bin/xdg-open
  #   stage-packages:
  #     - dbus

  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-3.3.4.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-debug
      - --disable-static
      - --enable-gpl
      - --enable-libvpx
      - --enable-libx264
      - --enable-shared
      - --enable-libxcb
      - --enable-libxcb-xfixes
      - --disable-libxcb-shape
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --disable-doc
      - --disable-everything
      - --enable-decoder=libvpx_vp8
      - --enable-decoder=rawvideo
      - --enable-encoder=libx264
      - --enable-encoder=libvpx_vp8
      - --enable-encoder=rawvideo
      - --enable-encoder=pam
      - --enable-demuxer=avi
      - --enable-muxer=mp4
      - --enable-muxer=webm
      - --enable-muxer=rawvideo
      - --enable-filter=crop
      - --enable-filter=scale
      - --enable-protocol=file
      - --enable-indev=xcbgrab
    build-packages:
      - libx264-dev
      - libvpx-dev
      - yasm
    stage-packages:
      - libx264-148
      - libvpx3
    prime:
      - -usr/share/applications
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/locale
      - -usr/share/man

  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick.git
    source-type: git
    source-tag: 6.9.9-12
    configflags:
      - --enable-static=no
      - --disable-docs
      - --disable-deprecated
      - --without-autotrace
      - --without-bzlib
      - --without-djvu
      - --without-dps
      - --without-fftw
      - --without-fontconfig
      - --without-fpx
      - --without-freetype
      - --without-gvc
      - --without-jbig
      - --without-jpeg
      - --without-lcms
      - --without-lzma
      - --without-magick-plus-plus
      - --without-openexr
      - --without-openjp2
      - --without-pango
      - --without-png
      - --without-raqm
      - --without-tiff
      - --without-webp
      - --without-wmf
      - --without-x
      - --without-xml
      - --without-zlib
    prime:
      - -bin/ffplay
      - -bin/ffprobe
      - -bin/ffserver
      - -bin/qt-faststart
      - -share/bug
      - -share/doc
      - -share/fonts
      - -share/locale
      - -share/man
    install: |
      sed -i s/avconv/ffmpeg/g $SNAPCRAFT_PART_INSTALL/etc/ImageMagick-6/delegates.xml
